import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { ClerkProvider } from '@clerk/nextjs'
import "./globals.css";
import Container from "@/components/Container/Container";
import NavBar from "@/components/NavBar/NavBar";
import UserContextProvider from "@/context/UserContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Affirmation",
  description: "Generated by Martin",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <UserContextProvider>
          <body className={inter.className}>
            <Container>
              <NavBar/>
            {children}
            </Container>
          </body>
        </UserContextProvider>
      </html>
    </ClerkProvider>
  );
}
